### ISSUE TITLE
CUB dataset' s caption

### ISSUE THREAD

**Issue by Auditor1234** [ExplainableML/ProbVLM#1]
I have downloaded the CUB dataset, but I don't know how to use <https://github.com/reedscot/cvpr2016> to generate test_c10, can anyone give me those captions files?

**Comment by Auditor1234** [comment]
I thought I have solved the problem, just mistaken the dataset.

**Comment by bravePinocchio** [comment]
How to solved this problem？

**Comment by bravePinocchio** [comment]
How to solve this problem？

**Comment by Auditor1234** [comment]
收到，谢谢
