### ISSUE TITLE
coco_vocab.pkl

### ISSUE THREAD

**Issue by yhelpq** [ExplainableML/ProbVLM#2]
Thank you for your contribution to open-source code! Is the current code runnable? There seem to be missing files, such as coco_vocab.pkl. Could you provide a reference documentation? Thank you very much!

**Comment by sgk98** [comment]
Hey,
While I don't think you should need these vocab files to run the code (commenting out their usages should be fine), they can be found here: https://github.com/naver-ai/pcme/tree/main/datasets/vocabs

**Comment by yhelpq** [comment]
Thank you for your reply. I'm sorry, I found this article quite interesting, but I'm not very familiar with this field, so I encountered many issues while running the code. When running src/train_ProbVLM_CLIP.ipynb, I got an error 'No such file or directory: 'ds/vocabs/coco_vocab.pkl',' which is why I thought I needed this vocab file. If I misunderstood, I apologize. I hope you can provide further guidance; I would greatly appreciate it. Additionally, may I ask, what is the difference between the 'da' folder and the 'da_lavis' folder? Thank you very much for your help; sorry for the inconvenience.




严
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ExplainableML/ProbVLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月27日(星期一) 凌晨1:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ExplainableML/ProbVLM] coco_vocab.pkl (Issue #2)





 
Hey,
 While I don't think you should need these vocab files to run the code (commenting out their usages should be fine), they can be found here: https://github.com/naver-ai/pcme/tree/main/datasets/vocabs

**Comment by sgk98** [comment]
Indeed, while the code currently requires the vocab files, you could either provide them from the provided link. Alternatively, you could comment out the loading of these files, since they are not used anywhere else. 

The folder `src/ds` contains the dataloaders that are used for the CLIP experiment, whereas the `src/ds_lavis` folder contains the files used for working with the BLIP model (which was done with the help of the LAVIS framework https://github.com/salesforce/LAVIS).  I hope this was useful for you and @udion should be able to help you out if you have any other questions about the codebase.

**Comment by yhelpq** [comment]
I appreciate your responses, and they have indeed contributed to a better understanding of this work. I apologize for the continued inquiry, but I have two additional inquiries that I would like to seek your guidance on. 

Firstly, in the train_probVLM.py file, what does the inclusion of the HF suffix in the function names signify? 
Secondly, in the validation function, it appears that only MSE and MAE metrics are included, while metrics such as ***@***.***, S, R2 and -SR2, commonly utilized in the referenced literature, seem to be absent. Is this due to incomplete implementation, or are there other reasons? I would greatly value your guidance on implementing these metrics. 


These two queries are pivotal for me, and I am grateful for your patient guidance and response. 


Thank you sincerely!





严
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ExplainableML/ProbVLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月29日(星期三) 凌晨1:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ExplainableML/ProbVLM] coco_vocab.pkl (Issue #2)





 
Indeed, while the code currently requires the vocab files, you could either provide them from the provided link. Alternatively, you could comment out the loading of these files, since they are not used anywhere else.
 
The folder src/ds contains the dataloaders that are used for the CLIP experiment, whereas the src/ds_lavis folder contains the files used for working with the BLIP model (which was done with the help of the LAVIS framework https://github.com/salesforce/LAVIS).  I hope this was useful for you and @udion should be able to help you out if you have any other questions about the codebase.

**Comment by sgk98** [comment]
From my understanding, the HF suffix are relating to the functions needed to work with the CLIP models provided by Huggingface (https://huggingface.co/docs/transformers/model_doc/clip) which works slightly differently from the CLIP codebase provided by OpenAI (https://github.com/openai/CLIP).

About the metrics, I think the implementations from Scipy (https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.spearmanr.html) and scikit-learn (https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html) were used. However, these metrics work on a dataset level and not for a single sample i.e you would need to compute the retrieval for a set of samples, bin them into different groups based on the uncertainty scores, and then compute the R@k for each bin, before using these metrics. You can contact @udion (uddeshya.upa@gmail.com) who can help you out with the exact details for this.
