### ISSUE TITLE
Evaluation code

### ISSUE THREAD

**Issue by asdffasdfaf** [ExplainableML/ProbVLM#3]
Hello, I couldn't find the evaluation code. Could you provide it?

Additionally, I noticed that the get_GGuncer function is inconsistent with the definition in the paper. Why is this the case?

**Comment by asdffasdfaf** [comment]
@sgk98 Please help me.

**Comment by asdffasdfaf** [comment]
@sgk98 I have already obtained the checkpoint. How can I obtain S and R2?

**Comment by udion** [comment]
Hi,

S and R^2 are just Spearman correlation and coefficient of determination between the uncertainty level and recall values.

So, if your uncertainty levels are U = [1,2,3,4,5] and recall valies are V = [v1, v2, v3, v4, v5], then,

S = scipy.stats.spearmanr(U, V)
R^2 = sklearn.metrics.r2_score(U, V)

**Comment by asdffasdfaf** [comment]
@udion @sgk98 Thank you. Could you provide the evaluation code, please?

Is the following code for calculating uncertainty correct? 


```python
def mean(tensor):
    log_tensor = torch.log(tensor)
    mean_log = torch.mean(log_tensor)
    geometric_mean = torch.exp(mean_log)
    return geometric_mean.item()

imdict=get_features_uncer_ProbVLM(CLIP_Net,ProbVLM_Net,cub_test_loader)
uncertainty=imdict['i_u']
uncertainty=[mean(i) for i in uncertainty]
```
The mean() function calculates the geometric mean.
