### ISSUE TITLE
The Function in the paper

### ISSUE THREAD

**Issue by ahustr** [ExplainableML/ProbVLM#6]
Thank you for your wonderful paper, but I have a question about a formula:
![image](https://github.com/ExplainableML/ProbVLM/assets/55874332/196749bb-1b3b-4234-a3b2-d55a4d4a7402)
In my understanding. If we ask for maximum likelihood, the parameters of the model have a certain value but are unknown, and we estimate it using a sample from the population, but you have a formula here where the parameters are constantly changing. If we look at the following equation in the paper:
![image](https://github.com/ExplainableML/ProbVLM/assets/55874332/bc3517a6-8ae9-4a52-ac8c-2ab7687b08f0)
You seem to have used only a single point for estimating the parameters.

**Comment by udion** [comment]
I am not sure I follow the question here, how is the above any different than learning \mu, \sigma of typical Gaussian with maximum likelihood?

Maybe refer here (aleatoric uncertainty), here: https://arxiv.org/pdf/1703.04977 which describes the similar process, but standard Gaussian.
